import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import { Inter, Noto_Sans, Nunito } from "next/font/google";

import React from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["cyrillic"],
  display: "swap",
});

const nunito = Nunito({
  subsets: ["cyrillic"],
  display: "swap",
});

const notoSans = Noto_Sans({
  subsets: ["cyrillic"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={notoSans.className}>
      <body>{children}</body>
      <Analytics />
    </html>
  );
}
